name: Project Tests
on:
  push:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.10"
        uses: actions/setup-python@v1
        with:
          version: "3.10"
      - name: Test
        run: python3 tests.py

